### ISSUE TITLE
Error 30001 when presenting card

### ISSUE THREAD

**Issue by hanseartic** [XRPL-Labs/tangem-sdk-react-native#13]
I've got a Nokia 8.1 running Android 11. When trying to scan my STELLAR-card the error `30001` is shown.

I verified that the card works by scanning with another phone (wileyfox, android 7).

Initially the error occured in the official Tangem App. I tried to verify if it's a problem with that app and built a dummy react-native app using https://github.com/XRPL-Labs/tangem-sdk-react-native (which is the one dowloaded through `npm i tangem-sdk-react-native`). But that showed the exact same dialog and also failed with error `30001`.

**Comment by WietseWind** [comment]
There's a known problem with the Nokias + Android. It's an NFC driver problem on the phones.
